### ISSUE TITLE
MUI에서 테마 적용 안됨

### ISSUE THREAD

**Issue by msdio** [msdio/stackticon#1]
## 📌 이슈 설명
Material UI에서 theme을 import 해서 사용할 경우 테마가 적용되지 않는 현상

### 🚴 이렇게 고쳐볼 수 있을 것 같아요
같은 파일에서 theme을 선언하고 사용하면 잘 됩니다. 뭔가 뭔가가 잘못된듯..

### 📷 스크린샷
![image](https://user-images.githubusercontent.com/59170680/218660042-53a92562-7efd-4459-a260-3d634610fcf0.png)

**Comment by userJu** [comment]
#2
