### ISSUE TITLE
Image URL undefined

### ISSUE THREAD

**Issue by userJu** [msdio/stackticon#106]
## 📌 Describe Issue
![3원하는저장방식으로](https://github.com/msdio/stackticon/assets/87933367/a93a1757-b290-40df-b5bf-9e3264dedaff)

- readme: `[![stackticon](undefined)](https://github.com/msdio/stackticon)`
- link only: `undefined`
- img: `<a href="https://github.com/msdio/stackticon"><img src="undefined" alt="stackticon" /></a>`

Image URL not found.
In firebase, I confirmed that the image is created well.

### 🐠 Checklists

- [  x ] Are image links created properly?
- [  x ] Does the same problem occur when selecting a different stack? ->` [![stackticon](undefined)](https://github.com/msdio/stackticon)`

### 🚴 Possible(or Suggest) solutions
I'm not sure because I haven't checked the code related to the issue yet,
There seems to be a problem in the process of receiving the image link.

### 🍳 Environments

- Device:
- OS:
- Browser:
- Version:

**Comment by msdio** [comment]
I checked test codes on utils, but it seems there is no problem with it.

Maybe it is not passing props properly to result page, I will take look on it.
