### ISSUE TITLE
forwardRef을 사용할 시 eslint 버그 발생

### ISSUE THREAD

**Issue by userJu** [msdio/stackticon#13]
## 📌 이슈 설명
Skills.tsx 파일에서 
```
Skills.displayName = 'Skills';
```
를 사용하지 않을 시
🚨
```
Component definition is missing display nameeslint[react/display-name](https://github.com/jsx-eslint/eslint-plugin-react/tree/master/docs/rules/display-name.md)
```
에러가 발생합니다

### 🐠 체크리스트

-   [ ]
-   [ ]

### 🚴 이렇게 고쳐볼 수 있을 것 같아요
`Skills.displayName = 'Skills';`를 사용하면 해결할 수 있습니다
더 좋은 해결방안이 있으면 말해주세요~🤗

### 🍳 이런 환경에서 발생했어요

-   Device:
-   OS:
-   Browser:
-   Version:

**Comment by msdio** [comment]
타입을 지정한다는 거죠? 만약에 title 정보를 사용한다면 타입을 `SimpleIcons['title']`로 하는건 어떤가요??

**Comment by msdio** [comment]
#16 에서 아래와 같이 해결되었습니다!

```tsx
const iconKey = target as keyof typeof icons;
```
