### ISSUE TITLE
stack이 선택되지 않았을 때 home으로 redirect시키는 과정 중 깜빡임 & /loading으로 직접 접근 시 에러

### ISSUE THREAD

**Issue by userJu** [msdio/stackticon#20]
## 📌 이슈 설명
#18 작업 내용 중 
-   [x] 사용자가 stack을 선택하지 않고 생성 버튼을 누를 시 loding창에서 home('/')으로 리다이렉트시키는 과정에서 깜빡임이 발생합니다.
-   [x] #28

### 🚴 이렇게 고쳐볼 수 있을 것 같아요
Loading 컴포넌트를 감싸는 LoadingContainer 컴포넌트를 제작해서 접근하는 방법을 생각했습니다
직접 /loading에 접근할 때도 처리할 수 있고 아무것도 없는 배열이 넘어왔을 때의 깜빡임도 해결할 수 있을 것 같습니다

### 🍳 이런 환경에서 발생했어요

-   Device:
-   OS:
-   Browser:
-   Version:

### 📷 스크린샷
![깜빡임](https://user-images.githubusercontent.com/87933367/219252504-325a27d9-2444-4d63-b556-57959ebd77d4.gif)

![에러](https://user-images.githubusercontent.com/87933367/219252544-6fa79986-077b-4bfa-bd94-4399000122a3.gif)

**Comment by msdio** [comment]
엥 아직 해결이 안된 것 같아요..! 직접 접근 시 `Cannot read properties of null (reading 'length')` 에러가 발생하네요.

**Comment by userJu** [comment]
> 엥 아직 해결이 안된 것 같아요..! 직접 접근 시 `Cannot read properties of null (reading 'length')` 에러가 발생하네요.

이 이슈는 #19 에서 해결했는데 #19 작업처럼 return시 컴포넌트가 아닌 Cute404 페이지를 보여주는 것이 아닌 router을 이용하자는 얘기가 나왔었죠?! router을 이용해서 다시 진행해볼게요!
