### ISSUE TITLE
[Bug] result 페이지에서 뒤로가기 시 loading 페이지로 이동

### ISSUE THREAD

**Issue by dev-redo** [msdio/stackticon#41]
## 📌 이슈 설명
result 페이지에서 뒤로가기를 누르면 로딩중으로 넘어간다음 다시 result 페이지로 돌아갑니다.
메인 화면으로 돌아가리라 판단했는데, 혹시 의도하신 유저스토리라면 죄송합니다..!!

### 📷 스크린샷
https://user-images.githubusercontent.com/69149030/219857173-73086817-8aa5-46a5-9921-5d2639d57813.mp4

(노래를 듣다가 녹화한거라 소리가 들어갔네요..)

### 🚴 이렇게 고쳐볼 수 있을 것 같아요
만약 메인 화면으로 돌아가는 걸 의도하신 것이라면, loading 파라미터를 따로 놔두지 않고 result 파라미터만 두면 처리하면 해결될 듯 합니다!

즉 loading중일 때에도 result 파라미터인것이죠!

**Comment by msdio** [comment]
소중한 이슈 감사합니다! 해당 이슈는 뒤로 가기 버튼을 누를 경우 메인 화면으로 가도록 변경하겠습니다 :)
