### ISSUE TITLE
커스텀 아이콘 사용 시 viewBox 문제

### ISSUE THREAD

**Issue by msdio** [msdio/stackticon#42]
## 📌 이슈 설명
기존 아이콘들은 viewBox가 `0 0 24 24`로 설정되어 있습니다. 
viewBox가 `0 0 305 305`와 같이 설정되어 있다면 viewBox가 변환되며 svg가 보이지 않습니다..

### 🐠 체크리스트

-   [x] java svg
-   [x] recoil svg

### 🍳 이런 환경에서 발생했어요

-   Device:
-   OS:
-   Browser:
-   Version:

**Comment by msdio** [comment]
현재까지 시도했던 방법들 정리합니다..

1. viewBox가 `0 0 24 24`인 아이콘을 찾자 -> 진짜 다 뒤져봤는데 없습니다..
2. svg의 viewBox 조작 시도 -> 실패
3. 커스텀 아이콘을 입력 받을 때 viewBox도 입력받기 -> 기존 simple icon들과 충돌..
4. simple icons 데이터 안에 있는 getter인 get svg() 함수 사용 -> div 태그를 직접 렌더링 할 수 없음
5. html 파일을 직접 파싱해서 뷰에 뿌려주는 `dangerouslySetInnerHTML` 이용 -> 보안 상 문제도 있다고 하고, viewBox 때문에 비율이 맞지 않아서 이미지가 잘리거나, 비율이 이상해짐, 이 방법은 결과를 만들 때도 문제가 많음
6. 이제 svg만 봐도 토할것같습니다....ㅜ

**Comment by msdio** [comment]
cx, cy 속성을 svg에 추가해줬더니 나타나긴 합니다..

cx, cy는 좌표 형태로 그래픽을 표현하는 svg의 중심점을 설정하는 값입니다.. 그런데 svg 사이즈와 결과 창에서의 아이콘을 위해서는 추가로 더 만져줘야 할 것 같아요

**Comment by msdio** [comment]
9. svg 바깥을 크기가 정해진 div로 감싸도 소용이 없습니다..

**Comment by msdio** [comment]
만약에.. 커스텀 svg에 viewBox props를 받는다면 기존 아이콘들의 viewBox는 모듈을 직접 만져야 할까요..?

**Comment by msdio** [comment]
![image](https://user-images.githubusercontent.com/59170680/219878769-8824e9ce-d6aa-4fff-a754-3b74d04a84a5.png)

일단 dropdown 쪽은 성공했습니다.. 뒤쪽 로직도 다 바꿔줘야 할 것 같아요

**Comment by msdio** [comment]
dropdown에서는 array, 뒤에 로딩에서 이미지를 만들 때는 객체 형태로 아이콘들을 선언하고 있어서

**Comment by msdio** [comment]
![image](https://user-images.githubusercontent.com/59170680/219880927-3652b42b-982d-4eb6-b479-2bfee35fe9dc.png)

업로드는 되는데, 결과 창에서 svg를 인식하지 못하고 있습니다.

**Comment by msdio** [comment]
![image](https://user-images.githubusercontent.com/59170680/219881693-63f73a5a-aa80-40ea-8b90-7d8662cc5cbd.png)

아... 성공했습니다.......ㅜ

**Comment by userJu** [comment]
오오 제가 pr을 읽으면서 가졌던 모든 의문점들이 한번에 정리되어있네요..! 제가 내일 다시 한번 읽어보고 제대로 리뷰 남기겠습니다!
