### ISSUE TITLE
모바일 레이아웃

### ISSUE THREAD

**Issue by msdio** [msdio/stackticon#49]
## 📚 작업 내용
생각보다 모바일로 들어오시는 분들이 꽤 있는 것 같아서.. 모바일 뷰 작업이 되면 좋을 것 같습니다!

**Comment by userJu** [comment]
좋아요! 저도 모바일로 접근했을 때 퀄리티가 떨어져보인다는 생각이 들어서 얘기해보고 싶었던 지점입니다👀
혹시 하루가 원하는 모바일 디자인 시안이나 아니디어가 있나요?

**Comment by msdio** [comment]
디자인 시안... 음... 피그마에서 한번 열심히 끄적어볼게요 ㅋㅋ...

**Comment by userJu** [comment]
> 디자인 시안... 음... 피그마에서 한번 열심히 끄적어볼게요 ㅋㅋ...

아니면 날짜를 잡고 같이 해보는건 어때요?!

**Comment by msdio** [comment]
> > 디자인 시안... 음... 피그마에서 한번 열심히 끄적어볼게요 ㅋㅋ...
> 
> 아니면 날짜를 잡고 같이 해보는건 어때요?!

좋아요! 그럼 주말에 ci cd 설정하려고 하는데 그 때 같이 하면 될 것 같아요
