### ISSUE TITLE
new feature : background color options

### ISSUE THREAD

**Issue by msdio** [msdio/stackticon#54]
## 📚 작업 내용
- choose background color : make user confirm before upload to firebase

## ✔ 체크리스트
- black, white, transparent
- container background color, font color, bg color of each stack

**Comment by userJu** [comment]
하루 [이 부분](https://github.com/msdio/stackticon/discussions/48#discussioncomment-5086383) 시간 될 때 한번 얘기해볼래요??

**Comment by msdio** [comment]
> 하루 [이 부분](https://github.com/msdio/stackticon/discussions/48#discussioncomment-5086383) 시간 될 때 한번 얘기해볼래요??

넵 편할때 불러주세요~
