### ISSUE TITLE
Image size is differ depend on device

### ISSUE THREAD

**Issue by msdio** [msdio/stackticon#64]
## 📌 Describe Issue
![image](https://user-images.githubusercontent.com/59170680/224197130-e5ae2882-d907-4248-a96f-6155ade441ca.png)

### 🐠 Checklists

- [ ]
- [ ]

### 🚴 Possible(or Suggest) solutions
I checked that we already make it into fixed size (width='700px' height='auto'), we gotta find another way to fix this.

### 🍳 Environments

- Device:
- OS:
- Browser:
- Version:

### 📷 Screenshots
** Big size **
[![stackticon](https://firebasestorage.googleapis.com/v0/b/stackticon-81399.appspot.com/o/images%2F1678263893096?alt=media&token=2e6456ca-dafc-42dd-89f9-1f6c7a4e0cce)](https://github.com/msdio/stackticon)

** Small size **
[![stackticon](https://firebasestorage.googleapis.com/v0/b/stackticon-81399.appspot.com/o/images%2F1678374330422?alt=media&token=8f5a4f64-3a6f-4e66-9e7d-f68baaeacf2a)](https://github.com/msdio/stackticon)

**Comment by userJu** [comment]
* for test

1. bigsize

<a href="https://github.com/msdio/stackticon"><img src="https://firebasestorage.googleapis.com/v0/b/stackticon-81399.appspot.com/o/images%2F1680086242303?alt=media&token=6881dc91-3b27-41dd-975f-1eaea0bc7291" alt="stackticon" /></a>

[![stackticon](https://firebasestorage.googleapis.com/v0/b/stackticon-81399.appspot.com/o/images%2F1680086242303?alt=media&token=6881dc91-3b27-41dd-975f-1eaea0bc7291)](https://github.com/msdio/stackticon)

2. smallsize

<a href="https://github.com/msdio/stackticon"><img src="https://firebasestorage.googleapis.com/v0/b/stackticon-81399.appspot.com/o/images%2F1680086064203?alt=media&token=4d207bff-1a2c-436d-a73e-874505bdb653" alt="stackticon" /></a>

[![stackticon](https://firebasestorage.googleapis.com/v0/b/stackticon-81399.appspot.com/o/images%2F1680086064203?alt=media&token=4d207bff-1a2c-436d-a73e-874505bdb653)](https://github.com/msdio/stackticon)

**Comment by userJu** [comment]
1. When I made the stacks where the problem occurred, the same problem did not appear => I excluded the assumption that the icon was the problem.

2. When comparing the size by accessing the image URL, the images created by haru are different in size.
big: 1400*444
Small: 700*252
was

the size i made
Both big and small: 560*227.

I guess I need to know at what point the size changes

**Comment by userJu** [comment]
This is the image result made with Galaxy Note 10
![](https://firebasestorage.googleapis.com/v0/b/stackticon-81399.appspot.com/o/images%2F1680087835306?alt=media&token=f33ea490-2c49-482f-acd6-a6513609af83)

An image of 1836*681 size came out.

I think it might be related to device size.

**Comment by userJu** [comment]
I thought about adjusting the height of Stacks.tsx to a certain height rather than auto.
Attempt Result: Failed

This is the result made with IphoneX
![](https://firebasestorage.googleapis.com/v0/b/stackticon-81399.appspot.com/o/images%2F1680088822309?alt=media&token=c306779c-d6cc-46fb-9a1d-9a2176ad0f7b)
