### ISSUE TITLE
 Where the part covered by BackgroundCircle is not selected

### ISSUE THREAD

**Issue by userJu** [msdio/stackticon#74]
## 📌 Describe Issue
A bug where the part covered by BackgroundCircle is not selected

### 🚴 Possible(or Suggest) solutions
- I think it can be solved by adjusting the z-index.

### 🍳 Environments

- Device:
- OS:
- Browser:
- Version:

**Comment by msdio** [comment]
can you let me know page that error is occuring? I guess it's background select page 🤔

**Comment by msdio** [comment]
also I'd be glad if you attach screenshots
