### ISSUE TITLE
리액트 컴포넌트를 image file로 만드는 방법

### ISSUE THREAD

**Issue by msdio** [msdio/stackticon#8]
@userJu 가 말했던 https://github.com/niklasvh/html2canvas 는 마지막 업데이트가 1년 전이라.. 
최근에 업데이트 되고 있는 라이브러리 중에 https://github.com/bubkoo/html-to-image 가 있긴 해요.

라이브러리를 안쓰고 할 수 있는 방법을 찾아보는게 베스트일텐데, 일단 정 안되면 라이브러리 쓰는걸로!

다른 정보 찾으면 여기다 계속 업데이트 해주세요!

**Comment by userJu** [comment]
하루가 가져온 [html-to-image](https://github.com/bubkoo/html-to-image) 라이브러리 공식문서 읽어봤어요!
html => canvas 뿐만 아니라 Blob랑 픽셀까지 지원해주네요!!😮 크게 고려할 사항이 없다면 사용해도 좋을 것 같아요!
그나저나 하루 라이브러리 업데이트 기간도 보고.. 멋찐개발자네여..👍 생각도 못해본 지점... 리스팩
